// Code generated by mockery v2.23.1. DO NOT EDIT.

package service

import (
	domain "hte-danger-zone-job/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAlarmService is an autogenerated mock type for the AlarmService type
type MockAlarmService struct {
	mock.Mock
}

// Send provides a mock function with given fields: body
func (_m *MockAlarmService) Send(body *domain.SendAlarmReq) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.SendAlarmReq) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockAlarmService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAlarmService creates a new instance of MockAlarmService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAlarmService(t mockConstructorTestingTNewMockAlarmService) *MockAlarmService {
	mock := &MockAlarmService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
