// Code generated by mockery v2.23.1. DO NOT EDIT.

package service

import (
	defines "hte-danger-zone-job/internal/defines"
	domain "hte-danger-zone-job/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockZoneService is an autogenerated mock type for the ZoneService type
type MockZoneService struct {
	mock.Mock
}

// Verify provides a mock function with given fields: deviceID, p
func (_m *MockZoneService) Verify(deviceID string, p *domain.Payload) (*defines.ResponseStatus, error) {
	ret := _m.Called(deviceID, p)

	var r0 *defines.ResponseStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *domain.Payload) (*defines.ResponseStatus, error)); ok {
		return rf(deviceID, p)
	}
	if rf, ok := ret.Get(0).(func(string, *domain.Payload) *defines.ResponseStatus); ok {
		r0 = rf(deviceID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*defines.ResponseStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *domain.Payload) error); ok {
		r1 = rf(deviceID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockZoneService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockZoneService creates a new instance of MockZoneService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockZoneService(t mockConstructorTestingTNewMockZoneService) *MockZoneService {
	mock := &MockZoneService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
